version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: pesuresearch
      POSTGRES_PASSWORD: pesuresearch
      POSTGRES_DB: pesuresearch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped 

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_container
    ports:
      - "5500:5500"
    volumes:
      - ./backend_new:/app
      - /app/node_modules
    environment:
      DB_URL: postgres://pesuresearch:pesuresearch@postgres:5432/pesuresearch
      JWT_SECRET_KEY: '123456789'
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_new:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin 
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    name: postgres_data_volume 
    external: false 
  pgadmin_data:
    name: pgadmin_data_volume  
    external: false 