# Use Node.js base image
FROM node:23.3.0-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend_new/package*.json ./

# Install dependencies
RUN npm install --force

# Copy application files
COPY frontend_new/ .

# Build the Next.js application

# Expose port for the Next.js app
EXPOSE 3000

# Start the application
CMD ["npm","run","dev"]