


import sys
import os
import pandas as pd
import requests
from datetime import datetime
import numpy as np
import json


if len(sys.argv) != 3:
    print("Usage: python seed.py <path_to_excel_file> <api_url>")
    sys.exit(1)

journal_api_url = sys.argv[1]
conference_api_url = sys.argv[2]


journal= [
  {
    "title": "Reinforcement Learning based Optimized Multi-path Load Balancing for QoS Provisioning in IoT",
    "name":"Dr. Sarasvathi V",
    "teacherIds": [
    ],
    "journalName": "International Journal of Computing and Digital Systems",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN: 2210-142X",
    "websiteLink": "",
    "articleLink": "http://dx.doi.org/10.12785/ijcds/130120",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Reinforcement",
      "Learning",
      "based",
      "Optimized",
      "Multi-path"
    ],
    "domain": "CSE"
  },
  {
    "title": "Real Time Patient Vital Monitoring and Alarm System with Prediction of Anomalies and Future Clinical Episodes using Machine Learning Models",
    "name": "J Ruby Dinakar",
    "teacherIds": [
    ],
    "journalName": "Journal of Advanced Research in Applied Mechanics",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 2289-7895",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.37934/aram.109.1.7383",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Real",
      "Time",
      "Patient",
      "Vital",
      "Monitoring"
    ],
    "domain": "CSE"
  },
  {
    "title": "Document Forgery Detection",
    "name": "Vandana Mevaldas Ladwani",
    "teacherIds": [
    ],
    "journalName": "International Journal of Engineering and Advanced Technology",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 2249-8958",
    "websiteLink": "",
    "articleLink": "http://doi.org/10.35940/ijeat.E4165.0612523",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Document",
      "Forgery",
      "Detection"
    ],
    "domain": "CSE"
  },
  {
    "title": "LFWE: Linguistic Feature Based Word Embedding for Hindi Fake News Detection",
    "name": "Dr. Arti Arya",
    "teacherIds": [
    ],
    "journalName": "ACM Transactions on Asian and Low-Resource Language Information Processing",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 2375-4702",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.1145/3589764",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "LFWE:",
      "Linguistic",
      "Feature",
      "Based",
      "Word"
    ],
    "domain": "CSE"
  },
  {
    "title": "Helmet Violation and Number Plate Detection System",
    "name": "Dr. Prajwala Ranganath Talanki",
    "teacherIds": [
    ],
    "journalName": "Grenze International Journal of Engineering and Technology, June Issu",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 2395 - 5295",
    "websiteLink": "",
    "articleLink": "",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Helmet",
      "Violation",
      "and",
      "Number",
      "Plate"
    ],
    "domain": "CSE"
  },
  {
    "title": "Multiple salient object detection through multi-level foreground segmentation strategy",
    "name": "Dr. Kokila P",
    "teacherIds": [
    ],
    "journalName": "International Journal of System Assurance Engineering and Management",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 0976-4348",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.1007/s13198-023-02058-0",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Multiple",
      "salient",
      "object",
      "detection",
      "through"
    ],
    "domain": "CSE"
  },
  {
    "title": "DALMIG: Matching-Based Data Center Allocation and Dual Live VM Migration in Cluster-Based Federated Cloud",
    "name": "Dr. Jeny Jijo",
    "teacherIds": [],
    "journalName": "IETE Journal of Research",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 0974-780X",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.1080/03772063.2023.2228754",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "DALMIG:",
      "Matching-Based",
      "Data",
      "Center",
      "Allocation"
    ],
    "domain": "CSE"
  },
  {
    "title": "An intelligent convolution based graph cut segmentation for potato leaf disease severity prediction",
    "name": "Dr. Clara Kanmani A",
    "teacherIds": [
    ],
    "journalName": "Multimedia Tools and Applications",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 1573-7721",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.1007/s11042-023-16718-7",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "An",
      "intelligent",
      "convolution",
      "based",
      "graph"
    ],
    "domain": "CSE"
  },
  {
    "title": "ALIS: A novel metric in lineage-independent evaluation of scholars",
    "name": "Dr. Sudeepa Roy Dey",
    "teacherIds": [
    ],
    "journalName": "Journal of Information Science, 49(4), 1007-1030.",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 1741-6485",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.1177/01655515211039",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "ALIS:",
      "A",
      "novel",
      "metric",
      "in"
    ],
    "domain": "CSE"
  },
  {
    "title": "Reliability Analysis of an IoT-Based Air Pollution Monitoring System Using Machine Learning Algorithm-BDBN",
    "name": "Dr. Saritha K",
    "teacherIds": [
      "Dr. Sarasvathi V"
    ],
    "journalName": "Journal of Cybernetics and Information Technologies",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN: 1314-4081",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.2478/cait-2023-0046",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Reliability",
      "Analysis",
      "of",
      "an",
      "IoT-Based"
    ],
    "domain": "CSE"
  },
  {
    "title": "A Novel Self-Exploration Scheme for Learning Optimal Policies against Dynamic Jamming Attacks in Cognitive Radio Networks",
    "name": "Dr. Sarasvathi V",
    "teacherIds": [
    ],
    "journalName": "Journal of Cybernetics and Information Technologies",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN: 1314-4081",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.2478/cait-2023-0040",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "A",
      "Novel",
      "Self-Exploration",
      "Scheme",
      "for"
    ],
    "domain": "CSE"
  },
  {
    "title": "Traffic Flow Prediction and Identifying Critical Node Networks Using Attention based Spectral Temporal Graph Neural Network",
    "name": "Dr. Sreenath M V",
    "teacherIds": [
    ],
    "journalName": "International Journal of Intelligent Engineering and Systems, Vol.16, No.6, 2023",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 2185-310X",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.22266/ijies2023.1231.78",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Traffic",
      "Flow",
      "Prediction",
      "and",
      "Identifying"
    ],
    "domain": "CSE"
  },
  {
    "title": "An improved IoT based security model for fitness tracker using quantum fruit fly optimization improved faster RCNN",
    "name": "Dr. Shanthala P T",
    "teacherIds": [
    ],
    "journalName": "International Journal of Information Technology",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 2511-2112",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.1007/s41870-023-01376-7",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "An",
      "improved",
      "IoT",
      "based",
      "security"
    ],
    "domain": "CSE"
  },
  {
    "title": "Eval - Automatic Evaluation of Answer Scripts using Deep Learning and Natural Language Processing",
    "name": "Dr. Geetha Dayalan",
    "teacherIds": [],
    "journalName": "International Journal of Intelligent Systems and Applications in Engineering",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 2147 - 6799",
    "websiteLink": "",
    "articleLink": "https://ijisae.org/index.php/IJISAE/article/view/2541",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Eval",
      "-",
      "Automatic",
      "Evaluation",
      "of"
    ],
    "domain": "CSE"
  },
  {
    "title": "Methods of Using Artificial Intelligence to Detect the Boundaries of Melanoma",
    "name": "Dr. Geetha Dayalan",
    "teacherIds": [
 
    ],
    "journalName": "Cardiometry",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "12",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.18137/cardiometry.2023.26.573579",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Methods",
      "of",
      "Using",
      "Artificial",
      "Intelligence"
    ],
    "domain": "CSE"
  },
  {
    "title": "Scheduling Framework for Resource Management inIoT Ecosystem Over 5G Network",
    "name": "Dr. Gauri Sameer Rapate",
    "teacherIds": [],
    "journalName": "International Journal of Computer Networks and Applications (IJCNA)",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN : 2395-0455",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.22247/ijcna/2023/218515",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Scheduling",
      "Framework",
      "for",
      "Resource",
      "Management"
    ],
    "domain": "CSE"
  },
  {
    "title": "Real-Time Streaming Analytics using Big Data Paradigm and Predictive Modelling based on Deep Learning",
    "name": "J Ruby Dinakar",
    "teacherIds": [],
    "journalName": "International Journal on Recent and Innovation Trends in Computing and Communication",
    "month": "January",
    "year": "2023",
    "volumeNo": "10",
    "issueNo": "0",
    "issn": "ISSN: 2321-8169",
    "websiteLink": "",
    "articleLink": "https://doi.org/10.17762/ijritcc.v11i4s.6323",
    "isUGC": False,
    "isScopus": False,
    "isWOS": False,
    "qNo": "NA",
    "impactFactor": "0",
    "isCapstone": False,
    "isAffiliating": False,
    "pageNumber": 0,
    "abstract": "Not provided",
    "keywords": [
      "Real-Time",
      "Streaming",
      "Analytics",
      "using",
      "Big"
    ],
    "domain": "CSE"
  }
]


conference=[
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "3rd International Conference on Recent Trends in Machine Learning, IoT, Smart Cities and Applications. Lecture Notes in Networks and Systems, vol 540. Springer, Singapore https://doi.org/10.1007/978-981-19-6088-8_7",
    "paperTitle": "Detection of Hello Flooding Attacks on RPL in Internet of Things Networks Using Different Machine Learning Algorithms",
    "proceedings_conference_title": "3rd International Conference on Recent Trends in Machine Learning, IoT, Smart Cities and Applications. Lecture Notes in Networks and Systems, vol 540. Springer, Singapore https://doi.org/10.1007/978-981-19-6088-8_7",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2367-3389Print ISSN2367-3370",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Detection",
      "Hello",
      "Flooding",
      "Attacks",
      "Internet"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "3rd International Conference on Recent Trends in Machine Learning, IoT, Smart Cities and Applications. Lecture Notes in Networks and Systems, vol 540. Springer, Singapore,https://doi.org/10.1007/978-981-19-6088-8_5",
    "paperTitle": "Analysis and Rendering of Deauthentication Attack Using IoT Technology",
    "proceedings_conference_title": "3rd International Conference on Recent Trends in Machine Learning, IoT, Smart Cities and Applications. Lecture Notes in Networks and Systems, vol 540. Springer, Singapore,https://doi.org/10.1007/978-981-19-6088-8_5",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2367-3389Print ISSN2367-3370",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Analysis",
      "Rendering",
      "Deauthentication",
      "Attack",
      "Using"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "3rd International Conference on Recent Trends in Machine Learning, IoT, Smart Cities and Applications. Lecture Notes in Networks and Systems, vol 540. Springer, Singapore,https://doi.org/10.1007/978-981-19-6088-8_8",
    "paperTitle": "Location Aided Secure Routing System in Ad-Hoc Networks",
    "proceedings_conference_title": "3rd International Conference on Recent Trends in Machine Learning, IoT, Smart Cities and Applications. Lecture Notes in Networks and Systems, vol 540. Springer, Singapore,https://doi.org/10.1007/978-981-19-6088-8_8",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2367-3389Print ISSN2367-3370",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Location",
      "Aided",
      "Secure",
      "Routing",
      "System"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Swati Pratap Jagdale",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "Third International Conference on Artificial Intelligence and Smart Energy (ICAIS)",
    "paperTitle": "Ingredients to Recipe: A YOLO-based Object Detector and Recommendation System via Clustering Approach",
    "proceedings_conference_title": "Third International Conference on Artificial Intelligence and Smart Energy (ICAIS)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:978-1-6654-6216-7",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "https://doi.org/10.1109/ICAIS56108.2023.10073769",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Ingredients",
      "Recipe",
      "based",
      "Object",
      "Detector"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Swati Pratap Jagdale",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "Third International Conference on Artificial Intelligence and Smart Energy (ICAIS)",
    "paperTitle": "Object Detection and Video Analyser for the Visually Impaired",
    "proceedings_conference_title": "Third International Conference on Artificial Intelligence and Smart Energy (ICAIS)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:978-1-6654-6216-7",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "https://doi.org/10.1109/ICAIS56108.2023.10073662",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Object",
      "Detection",
      "Video",
      "Analyser",
      "Visually"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Pooja Agarwal",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "ICMIP '23: Proceedings of the 2023 8th International Conference on Multimedia and Image Processing",
    "paperTitle": "Detail-Preserving Video-based Virtual Try-On (DPV-VTON)",
    "proceedings_conference_title": "ICMIP '23: Proceedings of the 2023 8th International Conference on Multimedia and Image Processing",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN: 978-1-4503-9958-6",
    "is_affiliating_institution_same": True,
    "publisherName": "ACM",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "https://doi.org/10.1145/3599589.3599599",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Detail",
      "Preserving",
      "Video",
      "based",
      "Virtual"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sandesh B J",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 International Conference on Emerging Smart Computing and Informatics (ESCI)",
    "paperTitle": "Hand Landmark Distance Based Sign Language Recognition using MediaPipe",
    "proceedings_conference_title": "2023 International Conference on Emerging Smart Computing and Informatics (ESCI)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:978-1-6654-7524-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "https://doi.org/10.1109/ESCI56872.2023.10100061",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Landmark",
      "Distance",
      "Based",
      "Language",
      "Recognition"
    ],
    "domain": "CSE"
  },
  {
    "name": "Deepti Chandrasekharan",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 2nd International Conference for Innovation in Technology (INOCON)",
    "paperTitle": "An IOTML Based Food Freshness Detection System",
    "proceedings_conference_title": "2023 2nd International Conference for Innovation in Technology (INOCON)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-2092-3",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "https://doi.org/10.1109/INOCON57975.2023.10101203",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "IOTML",
      "Based",
      "Freshness",
      "Detection",
      "System"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Geetha Dayalan",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 2nd International Conference for Innovation in Technology (INOCON)",
    "paperTitle": "Automated Script Evaluation using Machine Learning and Natural Language Processing",
    "proceedings_conference_title": "2023 2nd International Conference for Innovation in Technology (INOCON)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-2092-3",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "https://doi.org/10.1109/INOCON57975.2023.10101281",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Automated",
      "Script",
      "Evaluation",
      "using",
      "Machine"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Arti Arya",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 15th International Conference on Computer and Automation Engineering (ICCAE)https://doi.org/10.1109/ICCAE56788.2023.10111236",
    "paperTitle": "Attention based Evolutionary Approach for Image Classification",
    "proceedings_conference_title": "2023 15th International Conference on Computer and Automation Engineering (ICCAE)https://doi.org/10.1109/ICCAE56788.2023.10111236",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN: 2154-4360 Electronic ISBN:979-8-3503-9622-5",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Attention",
      "based",
      "Evolutionary",
      "Approach",
      "Image"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sarasvathi V",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT) https://doi.org/10.1109/I2CT57861.2023.10126295",
    "paperTitle": "Defending Against Identity Threats using Adaptive Authentication",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT) https://doi.org/10.1109/I2CT57861.2023.10126295",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Defending",
      "Against",
      "Identity",
      "Threats",
      "using"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sarasvathi V",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2024 IEEE 8th International Conference for Convergence in Technology (I2CT) https://doi.org/10.1109/I2CT57861.2023.10126441",
    "paperTitle": "Authentic Tweets Recommendation System",
    "proceedings_conference_title": "2024 IEEE 8th International Conference for Convergence in Technology (I2CT) https://doi.org/10.1109/I2CT57861.2023.10126441",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Authentic",
      "Tweets",
      "Recommendation",
      "System"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Prajwala Ranganath talanki",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT) https://doi.org/10.1109/I2CT57861.2023.10126440",
    "paperTitle": "Predicting the Number of Fatalities in an Air Crash",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT) https://doi.org/10.1109/I2CT57861.2023.10126440",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Predicting",
      "Number",
      "Fatalities",
      "Crash"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Prajwala Ranganath talanki",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 3rd International Conference on Smart Data Intelligence (ICSMDI)",
    "paperTitle": "Twitter Sentiment Analysis for Bitcoin Price Prediction",
    "proceedings_conference_title": "2023 3rd International Conference on Smart Data Intelligence (ICSMDI)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:978-1-6654-6487-1",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Twitter",
      "Sentiment",
      "Analysis",
      "Bitcoin",
      "Price"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Prajwala Ranganath talanki",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 3rd International Conference on Smart Data Intelligence (ICSMDI)",
    "paperTitle": "Automated Shopping Cart : Reducing Long Queues One Cart At A Time",
    "proceedings_conference_title": "2023 3rd International Conference on Smart Data Intelligence (ICSMDI)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:978-1-6654-6487-1",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Automated",
      "Shopping",
      "Reducing",
      "Queues"
    ],
    "domain": "CSE"
  },
  {
    "name": "Nivedita Kasturi",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "paperTitle": "Research Approaches for Building Analytics in Social Network towards Crowdsourcing",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Research",
      "Approaches",
      "Building",
      "Analytics",
      "Social"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. L Kamatchi Priya ",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "paperTitle": "Automatic Music Generation of Indian Classical Music based on Raga",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Automatic",
      "Music",
      "Generation",
      "Indian",
      "Classical"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Chandrashekhar Pomu Chavan",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "paperTitle": "Smart Farm Android Application Using IoT and Machine Learning",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Smart",
      "Android",
      "Application",
      "Using",
      "Machine"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Bharathi R",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "paperTitle": "Knowledge-Based Medical Tourism Recommender System",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Knowledge",
      "Based",
      "Medical",
      "Tourism",
      "Recommender"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sudeepa Roy Dey",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "paperTitle": "Scientific Knowledge Graph Creation and Analysis",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Scientific",
      "Knowledge",
      "Graph",
      "Creation",
      "Analysis"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Vinodha K",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "paperTitle": "Brain Tumour classification using Neural Kernel Machines",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "NA",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Brain",
      "Tumour",
      "classification",
      "using",
      "Neural"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sudeepa Roy Dey",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "paperTitle": "A Real-Time Adaptive Location-based Recommender System Integrating Personalities.",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "979-8-3503-3402-9",
    "is_affiliating_institution_same": True,
    "publisherName": "NA",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Adaptive",
      "Location",
      "based",
      "Recommender",
      "System"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Arti Arya",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 15th International Conference on Computer Modeling and Simulation",
    "paperTitle": "Swarm Learning in Autonomous Driving: A Privacy Preserving Approach",
    "proceedings_conference_title": "2023 15th International Conference on Computer Modeling and Simulation",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:9798400707919",
    "is_affiliating_institution_same": True,
    "publisherName": "ACM",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Swarm",
      "Learning",
      "Autonomous",
      "Driving",
      "Privacy"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sandesh B J",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Smart Computing and Communication (pp. 851-863). Singapore: Springer Nature Singapore",
    "paperTitle": "Near Real Time Crime Detection using intelligent Drone Capture and CNN's",
    "proceedings_conference_title": "International Conference on Smart Computing and Communication (pp. 851-863). Singapore: Springer Nature Singapore",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-99-0837-0• Online ISBN : 978-981-99-0838-7",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Crime",
      "Detection",
      "using",
      "intelligent",
      "Drone"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sreenath M V",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 International Conference on Distributed Computing and Electrical Circuits and Electronics (ICDCECE) (pp. 1-6)",
    "paperTitle": "Detection and Recognition of Animals Using Yolo Algorithm",
    "proceedings_conference_title": "2023 International Conference on Distributed Computing and Electrical Circuits and Electronics (ICDCECE) (pp. 1-6)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-4746-3",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Detection",
      "Recognition",
      "Animals",
      "Using",
      "Algorithm"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. L Kamatchi Priya ",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 International Conference on Advancement in Computation & Computer Technologies (InCACCT) (pp. 1-8)",
    "paperTitle": "Parkinson's Disease Prediction using Fisher Score based Recursive Feature Elimination",
    "proceedings_conference_title": "2023 International Conference on Advancement in Computation & Computer Technologies (InCACCT) (pp. 1-8)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-9649-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Parkinsons",
      "Disease",
      "Prediction",
      "using",
      "Fisher"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Chandrashekhar Pomu Chavan",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 2nd International Conference on Smart Technologies and Systems for Next Generation Computing (ICSTSN) (pp. 1-6)",
    "paperTitle": "Malware Detection Using Ensemble Learning and File Monitoring",
    "proceedings_conference_title": "2023 2nd International Conference on Smart Technologies and Systems for Next Generation Computing (ICSTSN) (pp. 1-6)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-4801-9",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Malware",
      "Detection",
      "Using",
      "Ensemble",
      "Learning"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Bharathi R",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 International Conference on Inventive Computation Technologies (ICICT) (pp. 1750-1757).",
    "paperTitle": "Anomaly Detection and Multi-Output Classification of IoT Attacks",
    "proceedings_conference_title": "2023 International Conference on Inventive Computation Technologies (ICICT) (pp. 1750-1757).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN: 2767-7788",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Anomaly",
      "Detection",
      "Multi",
      "Output",
      "Classification"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Bharathi R",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Smart Trends in Computing and Communications (pp. 717-726). Singapore",
    "paperTitle": "RtTSLC: A Framework for Real-Time Two-Handed Sign Language Translation",
    "proceedings_conference_title": "International Conference on Smart Trends in Computing and Communications (pp. 717-726). Singapore",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-99-0768-7• Online ISBN : 978-981-99-0769-4",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore.",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "RtTSLC",
      "Framework",
      "Handed",
      "Language",
      "Translation"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Kokila P",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 International Conference on Advancement in Computation & Computer Technologies (InCACCT) (pp. 784-789)",
    "paperTitle": "Gesture Recognition Glove For American Sign Language Using Accelerometers",
    "proceedings_conference_title": "2023 International Conference on Advancement in Computation & Computer Technologies (InCACCT) (pp. 784-789)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-9649-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Gesture",
      "Recognition",
      "Glove",
      "American",
      "Language"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Arti Arya",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 Third International Conference on Secure Cyber Computing and Communication (ICSCCC) (pp. 115-121).",
    "paperTitle": "Temples Restoration using Gated Convolution and Contextual Attention in Generative Adversarial Networks",
    "proceedings_conference_title": "2023 Third International Conference on Secure Cyber Computing and Communication (ICSCCC) (pp. 115-121).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-0072-7",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Temples",
      "Restoration",
      "using",
      "Gated",
      "Convolution"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sarasvathi V",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Advances in Computing and Data Sciences (pp. 529-542)",
    "paperTitle": "Spear Phishing Using Machine Learning",
    "proceedings_conference_title": "International Conference on Advances in Computing and Data Sciences (pp. 529-542)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-3-031-37939-0• Online ISBN : 978-3-031-37940-6",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Switzerland",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Spear",
      "Phishing",
      "Using",
      "Machine",
      "Learning"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Arti Arya",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "AIP Conference Proceedings (Vol. 2745, No. 1)",
    "paperTitle": "Discerning mental illnesses from social media posts using machine and deep learning algorithms",
    "proceedings_conference_title": "AIP Conference Proceedings (Vol. 2745, No. 1)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISSN : 0094-243X",
    "is_affiliating_institution_same": True,
    "publisherName": "AIP Publishing",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Discerning",
      "mental",
      "illnesses",
      "social",
      "media"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sudeepa Roy Dey",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 3rd International Conference on Advance Computing and Innovative Technologies in Engineering (ICACITE) (pp. 1297-1301)",
    "paperTitle": "Machine Learning in Preclinical Research: Prediction of Blood Brain Barrier Permeability",
    "proceedings_conference_title": "2023 3rd International Conference on Advance Computing and Innovative Technologies in Engineering (ICACITE) (pp. 1297-1301)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-9927-1",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Machine",
      "Learning",
      "Preclinical",
      "Research",
      "Prediction"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Kokila P",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Computer Vision and Robotics (pp. 487-497).",
    "paperTitle": "Synthesizing Music by Artist’s Style Transfer Using VQ-VAE and Diffusion Model",
    "proceedings_conference_title": "International Conference on Computer Vision and Robotics (pp. 487-497).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-99-4576-4• Online ISBN : 978-981-99-4577-1",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Synthesizing",
      "Music",
      "Artists",
      "Style",
      "Transfer"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. L Kamatchi Priya",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE International Conference on Contemporary Computing and Communications, (InC4) (Vol. 1, pp. 1-6).",
    "paperTitle": "Early Detection of Alzheimer's Disease using CNN with PSO for parameter optimization",
    "proceedings_conference_title": "2023 IEEE International Conference on Contemporary Computing and Communications, (InC4) (Vol. 1, pp. 1-6).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-3578-1",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Early",
      "Detection",
      "Alzheimers",
      "Disease",
      "using"
    ],
    "domain": "CSE"
  },
  {
    "name": "Deepti Chandrasekharan",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE International Conference on Contemporary Computing and Communications (InC4) (Vol. 1, pp. 1-5)",
    "paperTitle": "Estimation of Community Water Consumption Using Multivariate Ensemble Approach",
    "proceedings_conference_title": "2023 IEEE International Conference on Contemporary Computing and Communications (InC4) (Vol. 1, pp. 1-5)",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-3578-1",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Estimation",
      "Community",
      "Water",
      "Consumption",
      "Using"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Arti Arya",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Emerging Trends and Technologies on Intelligent Systems (pp. 133-145).",
    "paperTitle": "Multi-step Online Hate Speech Detection and Classification Using Sentiment and Sarcasm Features",
    "proceedings_conference_title": "International Conference on Emerging Trends and Technologies on Intelligent Systems (pp. 133-145).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-99-3962-6• Online ISBN : 978-981-99-3963-3",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore.",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Multi",
      "Online",
      "Speech",
      "Detection",
      "Classification"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sudeepa Roy Dey",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 International Conference on Network, Multimedia and Information Technology (NMITCON) (pp. 1-7).",
    "paperTitle": "Intelligent Traffic Systems: A Graph Analytics Approach for Sustainable Transportation Networks Using Bengaluru Traffic",
    "proceedings_conference_title": "2023 International Conference on Network, Multimedia and Information Technology (NMITCON) (pp. 1-7).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-0083-3",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Intelligent",
      "Traffic",
      "Systems",
      "Graph",
      "Analytics"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sandesh B J",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 4th Annual Flagship India Council International Subsections Conference",
    "paperTitle": "Generation of Controlled Face Images using Curated Datasets and StyleGAN2",
    "proceedings_conference_title": "2023 IEEE 4th Annual Flagship India Council International Subsections Conference",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-3356-5",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Generation",
      "Controlled",
      "Images",
      "using",
      "Curated"
    ],
    "domain": "CSE"
  },
  {
    "name": "J Ruby Dinakar",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 3rd International Conference on Pervasive Computing and Social Networking (ICPCSN) (pp.1661-1665))",
    "paperTitle": "Multispeaker and Multilingual Zero Shot Voice Cloning and Voice Conversion",
    "proceedings_conference_title": "2023 3rd International Conference on Pervasive Computing and Social Networking (ICPCSN) (pp.1661-1665))",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-2285-9",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Multispeaker",
      "Multilingual",
      "Voice",
      "Cloning",
      "Voice"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Vinodha K",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Worldwide Computing and Its Applications (pp. 177-189).",
    "paperTitle": "Disease Detection and Prediction in Plants Through Leaves Using Convolutional Neural Networks.",
    "proceedings_conference_title": "International Conference on Worldwide Computing and Its Applications (pp. 177-189).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-99-5880-1• Online ISBN : 978-981-99-5881-8",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Disease",
      "Detection",
      "Prediction",
      "Plants",
      "Through"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Arti Arya",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 14th International Conference on Computing Communication and Networking Technologies (ICCCNT) (pp. 1-7",
    "paperTitle": "Machine Learning Techniques for Fake News Detection in Low-Resource Hindi Language: A Comparative Study",
    "proceedings_conference_title": "2023 14th International Conference on Computing Communication and Networking Technologies (ICCCNT) (pp. 1-7",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN: 2473-7674",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Machine",
      "Learning",
      "Techniques",
      "Detection",
      "Resource"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "In 2023 7th International Conference on Computation System and Information Technology for Sustainable Solutions (CSITSS) (pp. 1-6).",
    "paperTitle": "Analysing the performance of 6LoWPAN- CoAP and RPL-CoAP on LoRaWAN in Constrained Environment",
    "proceedings_conference_title": "In 2023 7th International Conference on Computation System and Information Technology for Sustainable Solutions (CSITSS) (pp. 1-6).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-4315-1",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Analysing",
      "performance",
      "LoWPAN",
      "LoRaWAN",
      "Constrained"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 5th International Conference on Cybernetics, Cognition and Machine Learning Applications (ICCCMLA) (pp. 419-423).",
    "paperTitle": "Heterogeneous Data Prioritization in MAC RPL for Real-Time Health Monitoring and Personalized User Experiences in Wearable IoT Devices Integrating Mobility Models",
    "proceedings_conference_title": "2023 IEEE 5th International Conference on Cybernetics, Cognition and Machine Learning Applications (ICCCMLA) (pp. 419-423).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-3829-4",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Heterogeneous",
      "Prioritization",
      "Health",
      "Monitoring",
      "Personalized"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 5th International Conference on Cybernetics, Cognition and Machine Learning Applications (ICCCMLA) (pp. 413-418).",
    "paperTitle": "Disaster-Resilient Smart City Framework; A Cross-Layer Protocol Analysis for Emergency Earthquake Response",
    "proceedings_conference_title": "2023 IEEE 5th International Conference on Cybernetics, Cognition and Machine Learning Applications (ICCCMLA) (pp. 413-418).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-3829-4",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Disaster",
      "Resilient",
      "Smart",
      "Framework",
      "Cross"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Pooja Agarwal",
    "teacherIds": [
    "Dr. Arti Arya"    
    ],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Computational & Experimental Engineering and Sciences (pp. 1-13).",
    "paperTitle": "An Empirical Study on Privacy-Preserving Swarm Learning for Cataract Detection",
    "proceedings_conference_title": "International Conference on Computational & Experimental Engineering and Sciences (pp. 1-13).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-3-031-44946-8• Online ISBN : 978-3-031-44947-5",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Switzerland",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Empirical",
      "Study",
      "Privacy",
      "Preserving",
      "Swarm"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Pooja Agarwal",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Emerging Research in Computing, Information, Communication and Applications (pp. 541-556).",
    "paperTitle": "GAN-Based Image Restoration and Colorization",
    "proceedings_conference_title": "International Conference on Emerging Research in Computing, Information, Communication and Applications (pp. 541-556).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-99-7632-4• Online ISBN : 978-981-99-7633-1",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Based",
      "Image",
      "Restoration",
      "Colorization"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Saritha K",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Expert Clouds and Applications (pp. 683-696",
    "paperTitle": "Storage Automation Using the Interplanetary File System and RFID for Authentication",
    "proceedings_conference_title": "International Conference on Expert Clouds and Applications (pp. 683-696",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-99-1744-0Online ISBN : 978-981-99-1745-7",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Storage",
      "Automation",
      "Using",
      "Interplanetary",
      "System"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Saritha K",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "International Conference on Expert Clouds and Applications (pp. 77-96).",
    "paperTitle": "Automated Helpline Service Using a Two-Tier Ensemble Framework",
    "proceedings_conference_title": "International Conference on Expert Clouds and Applications (pp. 77-96).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-99-1744-0Online ISBN : 978-981-99-1745-7",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Automated",
      "Helpline",
      "Service",
      "Using",
      "Ensemble"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Alpha Vijayan",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2022 Fourth International Conference on Cognitive Computing and Information Processing (CCIP),IEEE Xplore: 31 March 2023",
    "paperTitle": "Advance Single Stage Convolutional Neural Network for Drug-Drug Interactions",
    "proceedings_conference_title": "2022 Fourth International Conference on Cognitive Computing and Information Processing (CCIP),IEEE Xplore: 31 March 2023",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-1-6654-5649-4● Online ISBN : 978-1-6654-5648-7",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Advance",
      "Single",
      "Stage",
      "Convolutional",
      "Neural"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Shanthala P T",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE International Conference on Contemporary Computing and Communications (InC4) (Vol. 1, pp. 1-6).",
    "paperTitle": "Evaluating the Effectiveness of Tree-based Machine Learning Classifiers for Cybersecurity Threat Detection",
    "proceedings_conference_title": "2023 IEEE International Conference on Contemporary Computing and Communications (InC4) (Vol. 1, pp. 1-6).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-3577-4",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Evaluating",
      "Effectiveness",
      "based",
      "Machine",
      "Learning"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Shanthala P T",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 International Conference on Advancement in Computation & Computer Technologies (InCACCT) (pp. 123-128).",
    "paperTitle": "IoT Botnet Creation and Detection using Machine Learning",
    "proceedings_conference_title": "2023 International Conference on Advancement in Computation & Computer Technologies (InCACCT) (pp. 123-128).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-9648-5",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Botnet",
      "Creation",
      "Detection",
      "using",
      "Machine"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Shanthala P T",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Library Automation System Using RFID Tags",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN: 9788770040723",
    "is_affiliating_institution_same": True,
    "publisherName": "NA",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Library",
      "Automation",
      "System",
      "Using"
    ],
    "domain": "CSE"
  },
  {
    "name": "Nivedita Kasturi",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Analysis on Potential Use of Crowdsourcing in Different Domain Using Metasynthesis",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-19-4192-4Online ISBN : 978-981-19-4193-1",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer,Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Analysis",
      "Potential",
      "Crowdsourcing",
      "Different",
      "Domain"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Geetha Dayalan",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 2nd International Conference for Innovation in Technology (INOCON) (pp. 1-6). IEEE.",
    "paperTitle": "Visualising Chemistry Experiments Using NLP and Computer Graphics",
    "proceedings_conference_title": "2023 2nd International Conference for Innovation in Technology (INOCON) (pp. 1-6). IEEE.",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-2092-3",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Visualising",
      "Chemistry",
      "Experiments",
      "Using",
      "Computer"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Jeny Jijo",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "AIP Conference Proceedings (Vol. 2916, No. 1).",
    "paperTitle": "A comparative study of task scheduling algorithms and a proposed tri-stage model for a federated cloud environment",
    "proceedings_conference_title": "AIP Conference Proceedings (Vol. 2916, No. 1).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISSN 1551-7616",
    "is_affiliating_institution_same": True,
    "publisherName": "AIP PUBLISHING",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "comparative",
      "study",
      "scheduling",
      "algorithms",
      "proposed"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Jeny Jijo",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "AIP Conference Proceedings (Vol. 2916, No. 1).",
    "paperTitle": "COVID-safe attendance monitoring system using QR codes, geo-location and IOT",
    "proceedings_conference_title": "AIP Conference Proceedings (Vol. 2916, No. 1).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISSN 1551-7616",
    "is_affiliating_institution_same": True,
    "publisherName": "AIP Publishing",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "COVID",
      "attendance",
      "monitoring",
      "system",
      "using"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE North Karnataka Subsection Flagship International Conference (NKCon) (pp. 1-6).",
    "paperTitle": "RPL-Powered Low-Power Lossy Networks: A Catalyst for Advancing Smart Grid Capabilities",
    "proceedings_conference_title": "2023 IEEE North Karnataka Subsection Flagship International Conference (NKCon) (pp. 1-6).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-1404-5",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Powered",
      "Power",
      "Lossy",
      "Networks",
      "Catalyst"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE North Karnataka Subsection Flagship International Conference (NKCon) (pp. 1-6). IEEE",
    "paperTitle": "Enhancing Disaster Response: A Study on SDN-Integrated Alarm and Alert Systems Using Cooja Simulations",
    "proceedings_conference_title": "2023 IEEE North Karnataka Subsection Flagship International Conference (NKCon) (pp. 1-6). IEEE",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-1404-5",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Enhancing",
      "Disaster",
      "Response",
      "Study",
      "Integrated"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE North Karnataka Subsection Flagship International Conference (NKCon) (pp. 1-6). IEEE.",
    "paperTitle": "HVSNA: An Advanced Hybrid Attack on RPL-Based Low-Power Wireless Networks",
    "proceedings_conference_title": "2023 IEEE North Karnataka Subsection Flagship International Conference (NKCon) (pp. 1-6). IEEE.",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-1404-5",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "HVSNA",
      "Advanced",
      "Hybrid",
      "Attack",
      "Based"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE North Karnataka Subsection Flagship International Conference (NKCon) (pp. 1-6). IEEE.",
    "paperTitle": "Analyzing the Impact of RPL Routing Attacks on the Smart City Ecosystems",
    "proceedings_conference_title": "2023 IEEE North Karnataka Subsection Flagship International Conference (NKCon) (pp. 1-6). IEEE.",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-1404-5",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Analyzing",
      "Impact",
      "Routing",
      "Attacks",
      "Smart"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "2023 International Conference on Evolutionary Algorithms and Soft Computing Techniques",
    "paperTitle": "Reinforcement Learning Employing a Multi-Objective Reward Function for SDN Routing Optimization",
    "proceedings_conference_title": "2023 International Conference on Evolutionary Algorithms and Soft Computing Techniques",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-1341-3",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Reinforcement",
      "Learning",
      "Employing",
      "Multi",
      "Objective"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Gauri Sameer Rapate",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "Computer Science On-line Conference (pp. 78-88).",
    "paperTitle": "Novel and Simplified Scheduling Approach for Optimized Routing Performance in Internet-of-Things",
    "proceedings_conference_title": "Computer Science On-line Conference (pp. 78-88).",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-3-031-35316-1Online ISBN : 978-3-031-35317-8",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer International Publishing",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Novel",
      "Simplified",
      "Scheduling",
      "Approach",
      "Optimized"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Vinodha K",
    "teacherIds": [
        "Dr. Geetha Dayalan"
    ],
    "totalAuthors": 1,
    "bookTitle": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT) (pp. 1-8). IEEE.",
    "paperTitle": "Framework for Improving the Accuracy of the Machine Learning Model in Predicting Future Values",
    "proceedings_conference_title": "2023 IEEE 8th International Conference for Convergence in Technology (I2CT) (pp. 1-8). IEEE.",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN:979-8-3503-3401-2",
    "is_affiliating_institution_same": True,
    "publisherName": "IEEE",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Framework",
      "Improving",
      "Accuracy",
      "Machine",
      "Learning"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sarasvathi V",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Document verification using blockchain",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN : 9781003363781",
    "is_affiliating_institution_same": True,
    "publisherName": "CRC Press",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Document",
      "verification",
      "using",
      "blockchain"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sarasvathi V",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Blockchain based higher education ecosystem",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISBN : 9781003363781",
    "is_affiliating_institution_same": True,
    "publisherName": "CRC Press",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Blockchain",
      "based",
      "higher",
      "education",
      "ecosystem"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Identifying and Predicting Sinkhole Attacks for Low-Power and Lossy IoT Networks",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-981-99-1766-2• Online ISBN : 978-981-99-1767-9",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Identifying",
      "Predicting",
      "Sinkhole",
      "Attacks",
      "Power"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Secure and Efficient Routing Mechanism for Healthcare Networks",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "978-981-99-1767-9",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Secure",
      "Efficient",
      "Routing",
      "Mechanism",
      "Healthcare"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Arti Arya",
    "teacherIds": [
    "Dr. Pooja Agarwal"    
    ],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Text Guided Facial Image Synthesis Using StyleGAN and Variational Autoencoder Trained CLIP",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Print ISBN : 978-3-031-42507-3• Online ISBN : 978-3-031-42508-0",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer Nature Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Guided",
      "Facial",
      "Image",
      "Synthesis",
      "Using"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. L Kamatchi Priya",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Parkinson's Disease Prediction Using Machine Learning",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "ISSN : 2327-3380",
    "is_affiliating_institution_same": True,
    "publisherName": "IGI GLOBAL",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Parkinsons",
      "Disease",
      "Prediction",
      "Using",
      "Machine"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Pooja Agarwal",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Recognition and Replacement of Handwritten Text into Digitized Text",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2367-3389Print ISSN2367-3370",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer, Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Recognition",
      "Replacement",
      "Handwritten",
      "Digitized"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Arti Arya",
    "teacherIds": [
        "Dr. Pooja Agarwal"
        ],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Privacy Preserving Early Disease Diagnosis in Human Nails Using Swarm Learning",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2190-3026Print ISSN2190-3018",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer, Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Privacy",
      "Preserving",
      "Early",
      "Disease",
      "Diagnosis"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Jeny Jijo",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Movie Recommendation System Using Hybrid Approach",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2367-3389Print ISSN2367-3370",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer, Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Movie",
      "Recommendation",
      "System",
      "Using",
      "Hybrid"
    ],
    "domain": "CSE"
  },
  {
    "name": "Animesh Giri",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Automating Audio Attack Vectors",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2367-3389Print ISSN2367-3370",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer, Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Automating",
      "Audio",
      "Attack",
      "Vectors"
    ],
    "domain": "CSE"
  },
  {
    "name": "Nivedita Kasturi",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Size Matters: Exploring the Impact of Model Architecture and Dataset Size on Semantic Segmentation of Abdominal Wall Muscles in CT Scans",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2367-3389Print ISSN2367-3370",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer, Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Matters",
      "Exploring",
      "Impact",
      "Model",
      "Architecture"
    ],
    "domain": "CSE"
  },
  {
    "name": "Nivedita Kasturi",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Detection of Natural Disasters Using Machine Learning and Computer Vision by Replacing the Need of Sensors",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2367-3389Print ISSN2367-3370",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer, Singapore",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Detection",
      "Natural",
      "Disasters",
      "Using",
      "Machine"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Pooja Agarwal",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "Social Media Interaction-Based Mental Health Analysis with a Chat-Bot User Interface.",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN1876-1119Print ISSN1876-1100",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Social",
      "Media",
      "Interaction",
      "Based",
      "Mental"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Sudeepa Roy Dey",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "A Novel Segmentation-Free Approach for Handwritten Sentence Recognition",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN1876-1119Print ISSN1876-1100",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Novel",
      "Segmentation",
      "Approach",
      "Handwritten",
      "Sentence"
    ],
    "domain": "CSE"
  },
  {
    "name": "Dr. Pooja Agarwal",
    "teacherIds": [],
    "totalAuthors": 1,
    "bookTitle": "NA",
    "paperTitle": "A Systematic Review and Future Perspective of Mental IllnessDetection Using Artificial Intelligence on Multimodal Digital Media",
    "proceedings_conference_title": "NA",
    "volumeNo": "1",
    "issueNo": "1",
    "year": "2023",
    "pageNumber": 0,
    "issn": "Electronic ISSN2367-3389Print ISSN2367-3370",
    "is_affiliating_institution_same": True,
    "publisherName": "Springer",
    "impactFactor": "0",
    "core": "NA",
    "link_of_paper": "",
    "isCapstone": True,
    "abstract": "Not provided",
    "keywords": [
      "Systematic",
      "Review",
      "Future",
      "Perspective",
      "Mental"
    ],
    "domain": "CSE"
  }
]


print("Started seeding journal data...")

for record in journal:
    try:
        # Use custom JSON dumps to handle serialization
        response = requests.post(
            journal_api_url, 
            data=json.dumps(record),
            headers={'Content-Type': 'application/json'}
        )
        
        if response.status_code == 201:
            print(f"successfully.")
        else:
            print(f"Failed : {response.text}")
    except Exception as e:
        print(f"Error: {e}")
        
 
print("Started seeding conference data...")       
        
for record in conference:
    try:
        # Use custom JSON dumps to handle serialization
        response = requests.post(
            conference_api_url, 
            data=json.dumps(record),
            headers={'Content-Type': 'application/json'}
        )
        
        if response.status_code == 201:
            print(f"successfully.")
        else:
            print(f"Failed : {response.text}")
    except Exception as e:
        print(f"Error: {e}")
        
        


        