export * from '../models/user';
export * from '../models/journal';
export * from '../models/conference';
export * from '../models/journalUser';
export * from '../models/patentUser';
export * from '../models/conferenceUser';
export * from '../models/patent';
export * from '../models/departmentConductedActivity';
export * from '../models/departmentAttendedActivity';
export * from '../models/studentSportsCultural';
export * from '../models/studentCareerCounselling'
export * from '../models/studentEntranceExam';
export * from '../models/studentHigherStudies';
export * from  '../models/interSports';
export * from  '../models/intraSports'
