import express from 'express';

import journal from './journal/api';
import conference from './conference/api';
import patent from './patent/api';
import auth from './auth/api';
import user from './user/api';
import departmentConductedActivity from './departmentConductedActivity/api';
import departmentAttendedActivity from './departmentAttendedActivity/api';
import studentCareerCounselling from './studentCareerCounselling/api';
import studentEntranceExam from './studentEntranceExam/api';
import studentHigherStudies from './studentHigherStudies/api';
import interSports from './interSports/api';
import intraSports from './intraSports/api';
import authenticateUser from '../middleware/authenticate-user';
import home from './home/api';
const router = express.Router();

router.use('/user', authenticateUser, user);
router.use('/home', home);
router.use('/journal', journal);
router.use('/conference', conference);
router.use('/patent', patent);
router.use('/auth', auth);
router.use('/departmentConductedActivity', departmentConductedActivity);
router.use('/departmentAttendedActivity', departmentAttendedActivity);
router.use('/studentEntranceExam', studentEntranceExam);
router.use('/studentHigherStudies', studentHigherStudies);
router.use('/interSports', interSports);
router.use('/intraSports', intraSports);
export default router;
